name: Generate and Deploy RSS Feed

on:
  schedule:
    # Запускать каждый час.
    # Это стандартный синтаксис Cron.
    # Например, '0 * * * *' означает "в 0 минут каждого часа, каждый день".
    # Можно изменить на '0 0 * * *' для ежедневного запуска в полночь и т.д.
    - cron: '0 * * * *'
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Скачиваем код из репозитория
      with:
        # Важно: Чтобы Action мог пушить изменения, нужно использовать токен с правами записи
        token: ${{ secrets.GITHUB_TOKEN }} # Стандартный токен GitHub с правами на запись

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Или 3.10, 3.11, в зависимости от предпочтений

    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Устанавливаем библиотеки из requirements.txt

    - name: Run Python script to generate RSS
      env:
        # Передаем API-ключ ScraperAPI как секрет
        # Это ОЧЕНЬ ВАЖНО для безопасности!
        SCRAPERAPI_API_KEY: ${{ secrets.SCRAPERAPI_API_KEY }}
      run: |
        python pepper_parser.py # Запускаем ваш Python-скрипт

    - name: Verify RSS file creation # Шаг отладки (можно убрать после успешной настройки)
      run: |
        echo "Listing files in current directory:"
        ls -l . # Показать файлы в текущей директории
        test -f pepper_feed.xml && echo "pepper_feed.xml exists!" || echo "pepper_feed.xml DOES NOT exist!"

    - name: Auto commit generated RSS feed # Использование готового Action для автоматического коммита и пуша
      uses: stefanzweifel/git-auto-commit-action@v5 # Используем готовый Action
      with:
        # Указываем файл, который нужно добавить и закоммитить
        file_pattern: 'pepper_feed.xml' 

        # Сообщение коммита
        commit_message: "Update RSS feed (Auto-commit by Action)" 
        
        # Принудительный пуш для решения проблем с расхождениями веток.
        # Используйте с осторожностью! Безопасно, если Action - единственный
        # источник изменений для pepper_feed.xml.
        push_options: '--force' 

        # Явно устанавливаем автора коммита как бота
        commit_user_name: 'github-actions[bot]'
        commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
