name: Generate and Deploy RSS Feed

on:
  schedule:
    # Запускать каждый час.
    # Это стандартный синтаксис Cron.
    # Например, '0 * * * *' означает "в 0 минут каждого часа, каждый день".
    - cron: '0 * * * *'
  workflow_dispatch: # Позволяет запускать вручную из вкладки Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Скачиваем код из репозитория
      with:
        # Важно: Чтобы Action мог пушить изменения, нужно использовать токен с правами записи
        token: ${{ secrets.GITHUB_TOKEN }} # Стандартный токен GitHub с правами на запись

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Или 3.10, 3.11, в зависимости от предпочтений

    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Устанавливаем библиотеки из requirements.txt

    - name: Run Python script to generate RSS
      env:
        SCRAPERAPI_API_KEY: ${{ secrets.SCRAPERAPI_API_KEY }}
      run: |
        python pepper_parser.py # Запускаем ваш Python-скрипт

    - name: Verify RSS file creation # Шаг отладки (можно убрать после успешной настройки)
      run: |
        echo "Listing files in current directory:"
        ls -l . # Показать файлы в текущей директории
        test -f pepper_feed.xml && echo "pepper_feed.xml exists!" || echo "pepper_feed.xml DOES NOT exist!"

    - name: Auto commit generated RSS feed # НОВЫЙ ШАГ для автоматического коммита и пуша
      uses: stefanzweifel/git-auto-commit-action@v5 # Используем готовый Action
      with:
        commit_message: "Update RSS feed (Auto-commit by Action)" # Сообщение коммита
        files: pepper_feed.xml # Файлы, которые нужно добавить и закоммитить
        # Дополнительные настройки можно добавить, если нужно, но для RSS этого достаточно.
        # Например, `branch: main` если нужно явно указать ветку
        # Если вы хотите пропустить CI/CD для этого коммита, добавьте в сообщение [skip ci]

